/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.monoxial.password_manager;

/**
 *
 * @author monoxial
 */
public class JDialog_NouveauCoffre extends javax.swing.JDialog {

    /**
     * Création d'un JDialog
     */
    JDialog_NouveauCoffre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_assistantNouveauCoffre = new javax.swing.JLabel();
        jLabel_NomCoffre = new javax.swing.JLabel();
        jTextField_nomCoffre = new javax.swing.JTextField();
        jButton_NouveauCoffre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_assistantNouveauCoffre.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel_assistantNouveauCoffre.setText("Assistant de création d'un coffre :");

        jLabel_NomCoffre.setText("Nom :");

        jButton_NouveauCoffre.setText("Créer un coffre");
        jButton_NouveauCoffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NouveauCoffreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_NouveauCoffre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_assistantNouveauCoffre, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_NomCoffre)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_nomCoffre)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_assistantNouveauCoffre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NomCoffre)
                    .addComponent(jTextField_nomCoffre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_NouveauCoffre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_NouveauCoffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NouveauCoffreActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_NouveauCoffreActionPerformed

    String showDialog() {
        setVisible(true);
        return jTextField_nomCoffre.getText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JDialog_NouveauCoffre dialog = new JDialog_NouveauCoffre(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_NouveauCoffre;
    private javax.swing.JLabel jLabel_NomCoffre;
    private javax.swing.JLabel jLabel_assistantNouveauCoffre;
    private javax.swing.JTextField jTextField_nomCoffre;
    // End of variables declaration//GEN-END:variables
}
