/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.monoxial.password_manager;

import static eu.monoxial.password_manager.JFrame_gestionnaire.calculForceMDP;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author monoxial
 */
public class JDialog_MotdepasseCoffre extends javax.swing.JDialog {

    /**
     * Creates new form JDialog_MotdepasseCoffre
     */
    JDialog_MotdepasseCoffre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Description = new javax.swing.JLabel();
        jLabel_MotDePasseCoffre = new javax.swing.JLabel();
        jPasswordField_ClefCoffre = new javax.swing.JPasswordField();
        jButton_Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_Description.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel_Description.setText("Veuillez saisir la clef du coffre :");

        jLabel_MotDePasseCoffre.setText("Mot de passe :");

        jButton_Valider.setText("Valider");
        jButton_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ValiderMDPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Valider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Description, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_MotDePasseCoffre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField_ClefCoffre)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Description)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MotDePasseCoffre)
                    .addComponent(jPasswordField_ClefCoffre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Valider)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ValiderMDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ValiderMDPActionPerformed
        if (jPasswordField_ClefCoffre.getPassword().length > 448) {
           JOptionPane.showMessageDialog(this, "Le mot de passe ne peut dépasser 448 caractères !", "Avertissement", JOptionPane.WARNING_MESSAGE);
        }
        else {
            this.dispose();
        }
    }//GEN-LAST:event_jButton_ValiderMDPActionPerformed

    char[] showDialog() {
        setVisible(true);
        return jPasswordField_ClefCoffre.getPassword();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog_MotdepasseCoffre dialog = new JDialog_MotdepasseCoffre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Valider;
    private javax.swing.JLabel jLabel_Description;
    private javax.swing.JLabel jLabel_MotDePasseCoffre;
    private javax.swing.JPasswordField jPasswordField_ClefCoffre;
    // End of variables declaration//GEN-END:variables
}
